# Python Tutorial - DSO 2019 Training

This tutorial is intended to guide people wishing to use Python to participate in the challenge.

It has 5 steps:

1. Importing data
2. Descriptive analysis
3. Data Preparation
4. Creating a template
5. Calculation of predictions and submissions

# Data Import

Let's install the necessary packages for this tutorial:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
pd.set_option('display.max_columns', 500)

In [2]:
%%time
X_train = pd.read_csv("data/X_train.csv", index_col=0, error_bad_lines=False)
X_test = pd.read_csv("data/X_test.csv", index_col=0, error_bad_lines=False)
y_train = pd.read_csv("data/y_train.csv", index_col=0)

b'Skipping line 2168: expected 31 fields, saw 33\nSkipping line 4822: expected 31 fields, saw 37\nSkipping line 4859: expected 31 fields, saw 37\nSkipping line 7342: expected 31 fields, saw 37\n'

Wall time: 425 ms

In [3]:
print("Dimension X_train:", X_train.shape)
print("Dimension X_test:", X_test.shape)

Dimension X_train: (8880, 30)
Dimension X_test: (2960, 30)

In [4]:
X_train.head(3)

,images_count,image_width,image_height,image_url,product_description,product_size,material,age,warranty,year,color,product_width,wifi,condition,product_length,shoe_size,vintage,brand,author,editor,product_height,weight,price,category,sub_category_1,sub_category_2,sub_category_3,sub_category_4,product_name,store_name
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,3,3458.0,2552.0,https://d1kvfoyrif6wzg.cloudfront.net/assets/i...,Superbe petit top bustier avec explosion de co...,44,100 % polyester,NaN,NaN,NaN,Multicolore,NaN,NaN,bon état,NaN,NaN,False,NaN,NaN,NaN,NaN,200.0,4.5,mode,"tops, t-shirts, débardeurs femme",NaN,NaN,NaN,Top bustier multicolore,Emmaüs 88 Neufchateau
1,2,2486.0,2254.0,https://d1kvfoyrif6wzg.cloudfront.net/assets/i...,"Radio ITT Océnic Flirt, année 70\nPour déco",NaN,Plastique,NaN,NaN,NaN,Jaune,NaN,NaN,en l'état,NaN,NaN,True,ITT Océanic,NaN,NaN,NaN,1000.0,15.0,mobilier - deco,bibelots et objets déco,NaN,NaN,NaN,Radio ITT Océanic,Communauté Emmaüs Thouars (magasin Parthenay)
2,3,1536.0,1536.0,https://d1kvfoyrif6wzg.cloudfront.net/assets/i...,Veste boléro à manches courtes NÛMPH. Gris chi...,40,"Polyester, coton, laine",NaN,NaN,NaN,Gris,NaN,NaN,neuf,NaN,NaN,False,Nûmph,NaN,NaN,NaN,360.0,16.0,label selection,mode,mode femme,NaN,NaN,NaN,Label Emmaüs Chambéry

# Descriptive analysis

## Structure of the datasets

The train dataset contains the characteristics and time of sale of **8880** items sold on the Emmaus website. It is this dataset that we will use to create a model. Each object is described by an observation of X variables. These variables are described in the ```description.pdf``` file in the USB key.

The test dataset contains the characteristics of **2960 objects**, which must be predicted for the time of sale. Unlike the train, the sell time is of course not filled in and an ```id``` column has been added to identify the predictions during the submission stage.

In [5]:
X_train.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
images_count,8880,NaN,NaN,NaN,3.63345,2.04857,0,2,3,5,29
image_width,8823,NaN,NaN,NaN,1807.82,1025.25,58,1000,1536,2448,5472
image_height,8823,NaN,NaN,NaN,1801.77,1101.21,64,970.5,1536,2448,5472
image_url,8823,8775,https://d1kvfoyrif6wzg.cloudfront.net/assets/i...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,8880,8836,"Relié, 48 pages, couverture usagée",6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_size,2414,33,38,402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
material,3947,1722,Coton,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,120,18,4a,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warranty,101,2,6 mois,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,1497,NaN,NaN,NaN,14810.1,496237,0,1979,1998,2007,1.92019e+07
color,5321,18,Multicolore,1063,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_width,107,NaN,NaN,NaN,42.0589,20.5453,10,30,40,46.5,140
wifi,83,2,True,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
condition,8856,5,bon état,4537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_length,90,NaN,NaN,NaN,65.2,36.2889,24,35.125,50,80,160
shoe_size,223,NaN,NaN,NaN,39.139,2.63781,25,37,39,41,48
vintage,5890,2,False,3832,NaN,NaN,NaN,NaN,NaN,NaN,NaN
brand,4329,2658,tmp,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
author,1412,1021,Hergé,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
editor,1437,655,Pocket,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_height,113,NaN,NaN,NaN,64.2788,33.4202,9,45.5,61,72,198
weight,8878,NaN,NaN,NaN,7794.86,82201.3,0.1,252,500,1000,2.2e+06
price,8880,NaN,NaN,NaN,21.5033,44.0243,0.5,6,10,20,2200
category,8879,11,mode,2982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sub_category_1,7292,169,mode,511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sub_category_2,3620,145,label selection,1132,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sub_category_3,927,124,les coups de coeur des vendeurs,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sub_category_4,70,37,les coups de coeur des vendeurs,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name,8064,7921,carte postale,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
store_name,8880,46,Emmaüs Lyon,895,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
y_train.duration.value_counts()

0    3027
2    2953
1    2900
Name: duration, dtype: int64

The dataset is very balanced, each of the 3 classes has a frequency close to 1/3.

# Model Creation

Now is the time to create a model. In this tutorial we will build a Random Forest.

To do this we use the variables ```["weight","price","nb_images","image_length","image_width","category"]```.

To avoid overfitting and estimate the true performance of our model we will use the criterion of cross-validation **k-fold** method (cross-validation).

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import LabelEncoder

### Imputation of missing values by the value "missing"

In [8]:
X_train.category.fillna('missing', inplace=True)
X_test.category.fillna('missing', inplace=True)

### Encoding categorical features

Machine learning algorithms expect to have **numbers** as input, not strings. That's why we turn **categorical features** into numbers, using ```LabelEncoder ()```

In [9]:
X_train.category.unique()

array(['mode', 'mobilier - deco', 'label selection', 'multimédia',
       'loisirs', 'enfance', 'librairie', 'culture - loisirs',
       'les coups de coeur des vendeurs', 'mobilier - deco - maison',
       'créations', 'missing'], dtype=object)

In [10]:
le = LabelEncoder()
X_train['category'] = le.fit_transform(X_train.category)
X_test['category'] = le.transform(X_test.category)

In [11]:
features = ["weight", "price", "images_count",
            "image_width", "image_height", "category"]

ppl = Pipeline([("imputer", Imputer(strategy='median')),
                ("clf", RandomForestClassifier(n_estimators=10))])

ppl.fit(X_train.loc[:, features], np.ravel(y_train))

pred_train = ppl.predict_proba(X_train.loc[:, features])
pred_cv = cross_val_predict(ppl, X_train.loc[:, features], np.ravel(y_train),
                            method='predict_proba', cv=5, n_jobs=-1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

# Calcul de l'erreur: logloss

In [12]:
from sklearn.metrics import log_loss

In [13]:
print("LogLoss on train sample:",log_loss(y_pred=pred_train, y_true=y_train))
print("LogLoss on train sample (CV):",log_loss(y_pred=pred_cv, y_true=y_train))

LogLoss on train sample: 0.29625210734455876
LogLoss on train sample (CV): 3.1504084002015773

# Calcul des predictions

In [14]:
pred_test = ppl.predict_proba(X_test.loc[:, features])

In [15]:
df_submission = pd.DataFrame(pred_test, index=X_test.index)

# Submission

## Possibility #1: via the QScore API

1. Go to the platform [QScore](https://qscore.datascience-olympics.com) then in "Submissions"> "Submit from your Python Notebook"
2. Get your TOKEN
3. Replace it in the function below and execute it

In [16]:
import io, math, requests

# Only works in Python3, see comment below for Python2
def submit_prediction(df, sep=',', **kwargs):
    # TOKEN to recover on the platform: "Submissions"> "Submit from your Python Notebook"
    TOKEN='ad30dbf801679bec096e2e1cb2c22196ac4f8ee4aabd83b0e820aa033ec347ac1db1f474bf754dfddf627c7d7ee78a62389bf48e19584f28bfea2a92aeb104c2'  
    URL='https://qscore.datascience-olympics.com/api/submissions'
    #buffer = io.BytesIO() # Python 2
    buffer = io.StringIO() # Python 3
    df.to_csv(buffer, sep=sep, **kwargs)
    buffer.seek(0)
    r = requests.post(URL, headers={'Authorization': 'Bearer {}'.format(TOKEN)},files={'datafile': buffer})
    if r.status_code == 429:
        raise Exception('Submissions are too close. Next submission is only allowed in {} seconds.'.format(int(math.ceil(int(r.headers['x-rate-limit-remaining']) / 1000.0))))
    if r.status_code != 200:
        raise Exception(r.text)

In [17]:
submit_prediction(df_submission, sep=',', index=True)

## Possibility #2: Submit a CSV file

1. Go to the platform [QScore](https://qscore.datascience-olympics.com) then in "Submissions"> "Submit with a file"
2. Deposit the CSV file

In [ ]:
df_submission.to_csv("my_prediction.csv", index_label="id", header=['0', '1', '2'])